version: '3.8'

services:
  backend:
    build:
      context: ./web/backend
    ports:
      - "3000:3000"
  
  frontend:
    build:
      context: ./web/frontend
    ports:
      - "5000:5000"
